version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: englishvoc_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: englishvoc
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: englishvoc_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: englishvoc
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: englishvoc_frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
